### ISSUE TITLE
Договориться про формат сообщений между клиентом и апи сервером

### ISSUE THREAD

**Issue by qs** [funtechhackday/zombolab#9]

**Comment by qs** [comment]
Сообщения от клиента:

Обновление карточек стратегий (просто отправляет весь список стратегий перезатирая предыдущие):
`PUT /users/1/cards`

Тело запроса:
```
{
	'cards': [
			'.TTTTT.
			 ..TTT..
			 ...T...
			 ...Z...
			 .......
			 .......
			 .......',
			'.......
			 .......
			 ...H...
			 ...Z...
			 .......
			 .......
			 .......'
	]
}
```

Получение карточек для текущего игрока
`GET /users/1/cards`
Ответ аналогичный запросу из POST выше


Отправка заявки на бой
`POST /fights` [BODY: uid: 1]

Ответ (ид боя) игрок добавляется в существующую неукомплектованную (<4 игроков) заявку, либо создается новая:
```
{
	"fight": 1
}
```

Получение данных о симуляции боя:
`GET /fights/1`

Ответ, если заявка еще не собрана (недостаточно игроков):
```
{
	"status": "waiting"
}
```
Ответ, если заявка набрана и ожидается результат симуляции:
```
{
	"status": "calculating"
}
```
Ответ, если заявка обработана:
```
{
	"status": "completed",
	"turns": [
		   'WWWWWWWWWW
			W..H...2.W
			W..T.W...W
			W.1......W
			WWWWWWWWWW',
		   'WWWWWWWWWW
			W.HT..2..W
			W.1T.W...W
			W........W
			WWWWWWWWWW',
		   'WWWWWWWWWW
			WH1T.2...W
			W..T.W...W
			W........W
			WWWWWWWWWW',
		   'WWWWWWWWWW
			W1TT2....W
			W..T.W...W
			W........W
			WWWWWWWWWW',
	]
}
```

**Comment by alexpts** [comment]
Залил все на сервер, доступно по адресу zombolab.com
